# Generated by Django 3.2.5 on 2021-08-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('description', models.TextField(default='', verbose_name='내용')),
                ('thumbnail', models.ImageField(default='', upload_to='./', verbose_name='사진')),
            ],
        ),
    ]
